# -*- coding: utf-8 -*-
"""Atividade_spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbPHbxhv_SwS-4F5b4rbI7DQKkw1wIbr

# Atividade Infraestrutura

## Ciencias de Dados 6º Semestre (FATEC VOTORANTIM)

Alunos:  
**Ana Elisa Rubinato**  
**Bruno Felipe Araujo**

Bloco 1: Leitura e exploração
"""

!pip install pyspark -q

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Atividade_Spark")  \
    .master("local[*]") \
    .getOrCreate()

print(f"Spark iniciado com sucesso: {spark.version}")

"""Exercício 1: Leitura dos arquivos"""

df_vendas = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("vendas_spark.csv")

df_clientes = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("clientes_spark.csv")

df_vendas.show(10)
df_vendas.printSchema()
print(f"O df_vendas possui {df_vendas.count()}")

df_clientes.show(10)
df_clientes.printSchema()
print(f"O df_clientes possui {df_clientes.count()}")

"""Exercício 2: Conferindo os tipos"""

# Verificando o tipo inferido das colunas de data
print(f"data_venda: {df_vendas.schema['data_venda'].dataType}")
print(f"data_cadastro: {df_clientes.schema['data_cadastro'].dataType}")

"""Bloco 2: Select e filtros (where)

Exercício 3: Seleção de colunas
"""

df_vendas.select(
    "produto",
    "categoria",
    "estado",
    "preco_unitario"
).show(15)

"""Exercício 4: Filtro simples"""

vendas_qtde_10 = df_vendas.where(
    df_vendas.quantidade == 10
)

vendas_qtde_10.show()

print(f"Total de vendas com quantidade igual a 10: {vendas_qtde_10.count()}")

"""Exercício 5: Filtro com múltiplas condições"""

df_vendas.select("id_venda", "produto", "estado", "preco_unitario") \
         .where(
             (df_vendas.preco_unitario >= 200) &
             (df_vendas.preco_unitario < 3000) &
             (df_vendas.estado == "SP")
         ).show()

"""Exercício 6: Filtro por categoria"""

# Descobrindo quais categorias existem
df_vendas.select("categoria").distinct().show()

df_vendas.select("produto", "categoria") \
         .where(df_vendas.categoria == "Eletronicos") \
         .distinct() \
         .show()

"""Bloco 3: Colunas calculadas

Exercício 7: Validando o valor total
"""

from pyspark.sql.functions import col, abs

df_vendas_validacao = df_vendas.withColumn(
    "valor_calculado",
    col("quantidade") * col("preco_unitario")
)

vendas_divergentes = df_vendas_validacao.where(
    abs(col("valor_calculado") - col("valor_total")) > 0.01
)

vendas_divergentes.select(
    "id_venda",
    "quantidade",
    "preco_unitario",
    "valor_total",
    "valor_calculado"
).show()

print(f"Quantidade de linhas divergentes: {vendas_divergentes.count()}")

"""Exercício 8: Extração de datas"""

from pyspark.sql.functions import year, month

df_vendas = df_vendas.withColumn(
    "ano_venda",
    year(col("data_venda"))
).withColumn(
    "mes_venda",
    month(col("data_venda"))
)

df_vendas.select(
    "id_venda",
    "data_venda",
    "ano_venda",
    "mes_venda"
).show(10)

"""Bloco 4: Agregações (groupBy)

Exercício 9: Total por categoria
"""

from pyspark.sql.functions import sum

vendas_por_categoria = df_vendas.groupBy(
    "categoria"
  ).agg(
      sum("valor_total")
      .alias("total_categorizado")
  ).orderBy(
      col("total_categorizado").desc()
  )

vendas_por_categoria.show()

"""Exercício 10: Resumo estatístico por categoria"""

from pyspark.sql.functions import(
    sum,
    count,
    avg,
    round
)

df_vendas_valores = df_vendas.groupBy(
    "categoria"
).agg(
    count("id_venda").alias("quantidade"),
    sum("quantidade").alias("qtde_vendida"),
    sum("valor_total").alias("total_vendas"),
    round(avg("valor_total"), 2).alias("media_venda")
)

df_vendas_valores.show()

"""Exercício 11: Agregação por duas dimensões"""

vendas_estado_categoria = df_vendas.groupBy(
    "estado",
    "categoria"
).agg(
    round(sum("valor_total"), 2).alias("total_vendido")
).orderBy(
    col("total_vendido").desc()
)

vendas_estado_categoria.show(10)

maior_receita = vendas_estado_categoria.first()

print(f"Maior receita: {maior_receita['estado']} / {maior_receita['categoria']} "
      f"com total de {maior_receita['total_vendido']}")

"""Exercício 12: Consulta SQL"""

df_vendas.createOrReplaceTempView("vendas")

resultado = spark.sql("""
    Select produto,
           round(sum(valor_total), 2) as total_vendido,
           count(id_venda) as qtde_vendas
    From vendas
    Group By produto
    Having sum(valor_total) > 1000000
    Order By total_vendido desc
""")

resultado.show()

"""Bloco 6: Joins

Exercício 13: Inner join
"""

resultado_inner = df_vendas.join(
    df_clientes,
    df_vendas.id_cliente == df_clientes.id_cliente,
    "inner"
)

resultado_select = resultado_inner.select(
    df_vendas["id_venda"],
    df_clientes["cliente"],
    df_clientes["cidade"],
    df_vendas["produto"],
    df_vendas["valor_total"]
)

resultado_select.show()

qtde_join = resultado_select.count()
qtde_vendas = df_vendas.count()

print(f"Linhas no inner join: {qtde_join}")
print(f"Linhas no df_vendas: {qtde_vendas}")
print(f"Registros perdidos: {qtde_vendas - qtde_join}")

"""**Analise:** o inner join retornou 50000 linhas, a mesma quantidade de `df_vendas`, portanto **nao houve perda de registros**.
O inner join mantem apenas as vendas cujo `id_cliente` existe em `df_clientes`; como todas as vendas possuem
um cliente cadastrado, nenhuma linha foi descartada. Caso houvesse vendas com `id_cliente` inexistente (ou nulo)
na tabela de clientes, essas linhas seriam perdidas no inner join.

Exercício 14: Left join e clientes sem compras
"""

resultado_left = df_clientes.join(
    df_vendas,
    df_clientes.id_cliente == df_vendas.id_cliente,
    "left"
)

clientes_sem_compras = resultado_left.where(
    df_vendas["id_venda"].isNull()
).select(
    df_clientes["id_cliente"],
    df_clientes["cliente"],
    df_clientes["data_cadastro"]
)

print(f"Clientes que nunca compraram: {clientes_sem_compras.count()}")

clientes_sem_compras.show(10)

"""Exercício 15: Join + agregação (ranking)"""

top_clientes = df_vendas.join(
    df_clientes,
    df_vendas.id_cliente == df_clientes.id_cliente,
    "inner"
).groupBy(
    df_clientes["id_cliente"],
    df_clientes["cliente"],
    df_clientes["cidade"]
).agg(
    count(df_vendas["id_venda"]).alias("qtde_compras"),
    round(sum(df_vendas["valor_total"]), 2).alias("total_gasto")
).orderBy(
    col("total_gasto").desc()
)

top_clientes.show(10)